// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: arc/apps/amp/api/amp.proto

package api

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PlayableFlags int32

const (
	Unknown        PlayableFlags = 0
	HasAudio       PlayableFlags = 4096
	HasVideo       PlayableFlags = 8192
	IsLive         PlayableFlags = 1
	IsSeekable     PlayableFlags = 2
	IsUnending     PlayableFlags = 4
	IsPlaylist     PlayableFlags = 8
	InternetRadio  PlayableFlags = 16
	PodcastEpisode PlayableFlags = 32
	AudioBook      PlayableFlags = 64
	RequiresWAN    PlayableFlags = 256
	RequiresLAN    PlayableFlags = 512
)

var PlayableFlags_name = map[int32]string{
	0:    "Unknown",
	4096: "HasAudio",
	8192: "HasVideo",
	1:    "IsLive",
	2:    "IsSeekable",
	4:    "IsUnending",
	8:    "IsPlaylist",
	16:   "InternetRadio",
	32:   "PodcastEpisode",
	64:   "AudioBook",
	256:  "RequiresWAN",
	512:  "RequiresLAN",
}

var PlayableFlags_value = map[string]int32{
	"Unknown":        0,
	"HasAudio":       4096,
	"HasVideo":       8192,
	"IsLive":         1,
	"IsSeekable":     2,
	"IsUnending":     4,
	"IsPlaylist":     8,
	"InternetRadio":  16,
	"PodcastEpisode": 32,
	"AudioBook":      64,
	"RequiresWAN":    256,
	"RequiresLAN":    512,
}

func (PlayableFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_945f4a3fc453958f, []int{0}
}

type LoginInfo struct {
	UserID       string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Pass         string `protobuf:"bytes,2,opt,name=Pass,proto3" json:"Pass,omitempty"`
	TokenValue   string `protobuf:"bytes,3,opt,name=TokenValue,proto3" json:"TokenValue,omitempty"`
	TokenExpires int64  `protobuf:"varint,4,opt,name=TokenExpires,proto3" json:"TokenExpires,omitempty"`
}

func (m *LoginInfo) Reset()      { *m = LoginInfo{} }
func (*LoginInfo) ProtoMessage() {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_945f4a3fc453958f, []int{0}
}
func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return m.Size()
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginInfo) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *LoginInfo) GetTokenValue() string {
	if m != nil {
		return m.TokenValue
	}
	return ""
}

func (m *LoginInfo) GetTokenExpires() int64 {
	if m != nil {
		return m.TokenExpires
	}
	return 0
}

type PlayableInfo struct {
	Title       string        `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Subtitle    string        `protobuf:"bytes,2,opt,name=Subtitle,proto3" json:"Subtitle,omitempty"`
	Artist      string        `protobuf:"bytes,3,opt,name=Artist,proto3" json:"Artist,omitempty"`
	Album       string        `protobuf:"bytes,4,opt,name=Album,proto3" json:"Album,omitempty"`
	ReleaseDate int64         `protobuf:"varint,5,opt,name=ReleaseDate,proto3" json:"ReleaseDate,omitempty"`
	Duration    float64       `protobuf:"fixed64,6,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Flags       PlayableFlags `protobuf:"varint,7,opt,name=Flags,proto3,enum=api.PlayableFlags" json:"Flags,omitempty"`
}

func (m *PlayableInfo) Reset()      { *m = PlayableInfo{} }
func (*PlayableInfo) ProtoMessage() {}
func (*PlayableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_945f4a3fc453958f, []int{1}
}
func (m *PlayableInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlayableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlayableInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlayableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayableInfo.Merge(m, src)
}
func (m *PlayableInfo) XXX_Size() int {
	return m.Size()
}
func (m *PlayableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayableInfo proto.InternalMessageInfo

func (m *PlayableInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PlayableInfo) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *PlayableInfo) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *PlayableInfo) GetAlbum() string {
	if m != nil {
		return m.Album
	}
	return ""
}

func (m *PlayableInfo) GetReleaseDate() int64 {
	if m != nil {
		return m.ReleaseDate
	}
	return 0
}

func (m *PlayableInfo) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PlayableInfo) GetFlags() PlayableFlags {
	if m != nil {
		return m.Flags
	}
	return Unknown
}

type MediaProviderInfo struct {
	CommonName           string `protobuf:"bytes,1,opt,name=CommonName,proto3" json:"CommonName,omitempty"`
	RequiresSubscription bool   `protobuf:"varint,2,opt,name=RequiresSubscription,proto3" json:"RequiresSubscription,omitempty"`
	RequiresInternet     bool   `protobuf:"varint,3,opt,name=RequiresInternet,proto3" json:"RequiresInternet,omitempty"`
}

func (m *MediaProviderInfo) Reset()      { *m = MediaProviderInfo{} }
func (*MediaProviderInfo) ProtoMessage() {}
func (*MediaProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_945f4a3fc453958f, []int{2}
}
func (m *MediaProviderInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MediaProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MediaProviderInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MediaProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaProviderInfo.Merge(m, src)
}
func (m *MediaProviderInfo) XXX_Size() int {
	return m.Size()
}
func (m *MediaProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MediaProviderInfo proto.InternalMessageInfo

func (m *MediaProviderInfo) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *MediaProviderInfo) GetRequiresSubscription() bool {
	if m != nil {
		return m.RequiresSubscription
	}
	return false
}

func (m *MediaProviderInfo) GetRequiresInternet() bool {
	if m != nil {
		return m.RequiresInternet
	}
	return false
}

func init() {
	proto.RegisterEnum("api.PlayableFlags", PlayableFlags_name, PlayableFlags_value)
	proto.RegisterType((*LoginInfo)(nil), "api.LoginInfo")
	proto.RegisterType((*PlayableInfo)(nil), "api.PlayableInfo")
	proto.RegisterType((*MediaProviderInfo)(nil), "api.MediaProviderInfo")
}

func init() { proto.RegisterFile("arc/apps/amp/api/amp.proto", fileDescriptor_945f4a3fc453958f) }

var fileDescriptor_945f4a3fc453958f = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6e, 0xda, 0x4c,
	0x14, 0x85, 0x3d, 0x04, 0x88, 0xb9, 0x09, 0x68, 0x32, 0x8a, 0x7e, 0x59, 0x59, 0x8c, 0x2c, 0x56,
	0x28, 0x0b, 0x90, 0xf2, 0x3f, 0x40, 0x43, 0x4a, 0xaa, 0x22, 0xd1, 0x08, 0x99, 0x90, 0xae, 0x07,
	0x3c, 0x45, 0x23, 0xcc, 0x8c, 0xeb, 0xb1, 0xd3, 0x56, 0xdd, 0xf0, 0x08, 0x95, 0xfa, 0x12, 0x55,
	0x9f, 0xa4, 0x4b, 0x56, 0x55, 0x96, 0xc5, 0x6c, 0xba, 0xcc, 0x23, 0x54, 0x33, 0x86, 0x88, 0xa8,
	0x5d, 0xd9, 0xdf, 0xb9, 0xd6, 0x3d, 0xe7, 0x8c, 0x35, 0x70, 0xc6, 0x92, 0x69, 0x87, 0xc5, 0xb1,
	0xee, 0xb0, 0x45, 0xdc, 0x61, 0xb1, 0x30, 0xcf, 0x76, 0x9c, 0xa8, 0x54, 0x91, 0x03, 0x16, 0x8b,
	0xe6, 0x67, 0xa8, 0x0d, 0xd4, 0x4c, 0xc8, 0xbe, 0x7c, 0xa7, 0xc8, 0x7f, 0x50, 0x1d, 0x6b, 0x9e,
	0xf4, 0x7b, 0x1e, 0xf2, 0x51, 0xab, 0x16, 0x6c, 0x89, 0x10, 0x28, 0x0f, 0x99, 0xd6, 0x5e, 0xc9,
	0xaa, 0xf6, 0x9d, 0x50, 0x80, 0x5b, 0x35, 0xe7, 0xf2, 0x8e, 0x45, 0x19, 0xf7, 0x0e, 0xec, 0x64,
	0x4f, 0x21, 0x4d, 0x38, 0xb6, 0x74, 0xfd, 0x31, 0x16, 0x09, 0xd7, 0x5e, 0xd9, 0x47, 0xad, 0x83,
	0xe0, 0x99, 0xd6, 0xfc, 0x89, 0xe0, 0x78, 0x18, 0xb1, 0x4f, 0x6c, 0x12, 0x71, 0x1b, 0xe0, 0x14,
	0x2a, 0xb7, 0x22, 0x8d, 0xf8, 0xd6, 0xbf, 0x00, 0x72, 0x06, 0xee, 0x28, 0x9b, 0xa4, 0x76, 0x50,
	0x44, 0x78, 0x62, 0x13, 0xb9, 0x9b, 0xa4, 0x42, 0xa7, 0xdb, 0x08, 0x5b, 0x32, 0x9b, 0xba, 0xd1,
	0x24, 0x5b, 0x58, 0xdf, 0x5a, 0x50, 0x00, 0xf1, 0xe1, 0x28, 0xe0, 0x11, 0x67, 0x9a, 0xf7, 0x58,
	0xca, 0xbd, 0x8a, 0xcd, 0xb4, 0x2f, 0x19, 0xaf, 0x5e, 0x96, 0xb0, 0x54, 0x28, 0xe9, 0x55, 0x7d,
	0xd4, 0x42, 0xc1, 0x13, 0x93, 0x16, 0x54, 0x5e, 0x45, 0x6c, 0xa6, 0xbd, 0x43, 0x1f, 0xb5, 0x1a,
	0x17, 0xa4, 0xcd, 0x62, 0xd1, 0xde, 0xe5, 0xb7, 0x93, 0xa0, 0xf8, 0xa0, 0xf9, 0x15, 0xc1, 0xc9,
	0x1b, 0x1e, 0x0a, 0x36, 0x4c, 0xd4, 0xbd, 0x08, 0x79, 0x62, 0xdb, 0x51, 0x80, 0x97, 0x6a, 0xb1,
	0x50, 0xf2, 0x86, 0x2d, 0x76, 0x15, 0xf7, 0x14, 0x72, 0x01, 0xa7, 0x01, 0x7f, 0x9f, 0x99, 0xa3,
	0x19, 0x65, 0x13, 0x3d, 0x4d, 0x44, 0x6c, 0x73, 0x98, 0xce, 0x6e, 0xf0, 0xcf, 0x19, 0x39, 0x07,
	0xbc, 0xd3, 0xfb, 0x32, 0xe5, 0x89, 0xe4, 0xc5, 0x49, 0xb8, 0xc1, 0x5f, 0xfa, 0xf9, 0x0a, 0x41,
	0xfd, 0x59, 0x5c, 0x72, 0x04, 0x87, 0x63, 0x39, 0x97, 0xea, 0x83, 0xc4, 0x0e, 0xa9, 0x83, 0xfb,
	0x9a, 0xe9, 0x6e, 0x16, 0x0a, 0x85, 0x97, 0xfe, 0x16, 0xef, 0x44, 0xc8, 0x15, 0x5e, 0x5e, 0x12,
	0x80, 0x6a, 0x5f, 0x0f, 0xc4, 0x3d, 0xc7, 0x88, 0x34, 0x00, 0xfa, 0x7a, 0xc4, 0xf9, 0xdc, 0x6c,
	0xc2, 0xa5, 0x82, 0xc7, 0x92, 0xcb, 0x50, 0xc8, 0x19, 0x2e, 0x17, 0x6c, 0x9c, 0x22, 0xa1, 0x53,
	0xec, 0x92, 0x13, 0xa8, 0xef, 0x42, 0x04, 0xcc, 0xac, 0xc7, 0x84, 0x40, 0x63, 0xa8, 0xc2, 0x29,
	0xd3, 0xe9, 0x75, 0x2c, 0xb4, 0x0a, 0x39, 0x36, 0x8e, 0x35, 0xeb, 0x7e, 0xa5, 0xd4, 0x1c, 0x5f,
	0x12, 0x6c, 0x7e, 0x56, 0x51, 0xe1, 0x6d, 0xf7, 0x06, 0x2f, 0x4b, 0xfb, 0xca, 0xc0, 0x28, 0xe5,
	0xab, 0x17, 0xab, 0x35, 0x75, 0x1e, 0xd6, 0xd4, 0x79, 0x5c, 0x53, 0xb4, 0xcc, 0x29, 0xfa, 0x96,
	0x53, 0xf4, 0x23, 0xa7, 0x68, 0x95, 0x53, 0xf4, 0x2b, 0xa7, 0xe8, 0x77, 0x4e, 0x9d, 0xc7, 0x9c,
	0xa2, 0x2f, 0x1b, 0xea, 0xac, 0x36, 0xd4, 0x79, 0xd8, 0x50, 0xe7, 0x7b, 0xc9, 0xed, 0x26, 0x53,
	0x1d, 0xb3, 0x29, 0x9f, 0x54, 0xed, 0x5d, 0xf8, 0xff, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50,
	0xfb, 0x2e, 0x39, 0x29, 0x03, 0x00, 0x00,
}

func (x PlayableFlags) String() string {
	s, ok := PlayableFlags_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *LoginInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginInfo)
	if !ok {
		that2, ok := that.(LoginInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if this.Pass != that1.Pass {
		return false
	}
	if this.TokenValue != that1.TokenValue {
		return false
	}
	if this.TokenExpires != that1.TokenExpires {
		return false
	}
	return true
}
func (this *PlayableInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PlayableInfo)
	if !ok {
		that2, ok := that.(PlayableInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.Subtitle != that1.Subtitle {
		return false
	}
	if this.Artist != that1.Artist {
		return false
	}
	if this.Album != that1.Album {
		return false
	}
	if this.ReleaseDate != that1.ReleaseDate {
		return false
	}
	if this.Duration != that1.Duration {
		return false
	}
	if this.Flags != that1.Flags {
		return false
	}
	return true
}
func (this *MediaProviderInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MediaProviderInfo)
	if !ok {
		that2, ok := that.(MediaProviderInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CommonName != that1.CommonName {
		return false
	}
	if this.RequiresSubscription != that1.RequiresSubscription {
		return false
	}
	if this.RequiresInternet != that1.RequiresInternet {
		return false
	}
	return true
}
func (this *LoginInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&api.LoginInfo{")
	s = append(s, "UserID: "+fmt.Sprintf("%#v", this.UserID)+",\n")
	s = append(s, "Pass: "+fmt.Sprintf("%#v", this.Pass)+",\n")
	s = append(s, "TokenValue: "+fmt.Sprintf("%#v", this.TokenValue)+",\n")
	s = append(s, "TokenExpires: "+fmt.Sprintf("%#v", this.TokenExpires)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PlayableInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&api.PlayableInfo{")
	s = append(s, "Title: "+fmt.Sprintf("%#v", this.Title)+",\n")
	s = append(s, "Subtitle: "+fmt.Sprintf("%#v", this.Subtitle)+",\n")
	s = append(s, "Artist: "+fmt.Sprintf("%#v", this.Artist)+",\n")
	s = append(s, "Album: "+fmt.Sprintf("%#v", this.Album)+",\n")
	s = append(s, "ReleaseDate: "+fmt.Sprintf("%#v", this.ReleaseDate)+",\n")
	s = append(s, "Duration: "+fmt.Sprintf("%#v", this.Duration)+",\n")
	s = append(s, "Flags: "+fmt.Sprintf("%#v", this.Flags)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MediaProviderInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&api.MediaProviderInfo{")
	s = append(s, "CommonName: "+fmt.Sprintf("%#v", this.CommonName)+",\n")
	s = append(s, "RequiresSubscription: "+fmt.Sprintf("%#v", this.RequiresSubscription)+",\n")
	s = append(s, "RequiresInternet: "+fmt.Sprintf("%#v", this.RequiresInternet)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAmp(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *LoginInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenExpires != 0 {
		i = encodeVarintAmp(dAtA, i, uint64(m.TokenExpires))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TokenValue) > 0 {
		i -= len(m.TokenValue)
		copy(dAtA[i:], m.TokenValue)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.TokenValue)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Pass) > 0 {
		i -= len(m.Pass)
		copy(dAtA[i:], m.Pass)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.Pass)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserID) > 0 {
		i -= len(m.UserID)
		copy(dAtA[i:], m.UserID)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.UserID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PlayableInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayableInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlayableInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Flags != 0 {
		i = encodeVarintAmp(dAtA, i, uint64(m.Flags))
		i--
		dAtA[i] = 0x38
	}
	if m.Duration != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Duration))))
		i--
		dAtA[i] = 0x31
	}
	if m.ReleaseDate != 0 {
		i = encodeVarintAmp(dAtA, i, uint64(m.ReleaseDate))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Album) > 0 {
		i -= len(m.Album)
		copy(dAtA[i:], m.Album)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.Album)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Artist) > 0 {
		i -= len(m.Artist)
		copy(dAtA[i:], m.Artist)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.Artist)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Subtitle) > 0 {
		i -= len(m.Subtitle)
		copy(dAtA[i:], m.Subtitle)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.Subtitle)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MediaProviderInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MediaProviderInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MediaProviderInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequiresInternet {
		i--
		if m.RequiresInternet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.RequiresSubscription {
		i--
		if m.RequiresSubscription {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.CommonName) > 0 {
		i -= len(m.CommonName)
		copy(dAtA[i:], m.CommonName)
		i = encodeVarintAmp(dAtA, i, uint64(len(m.CommonName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAmp(dAtA []byte, offset int, v uint64) int {
	offset -= sovAmp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LoginInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserID)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	l = len(m.Pass)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	l = len(m.TokenValue)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	if m.TokenExpires != 0 {
		n += 1 + sovAmp(uint64(m.TokenExpires))
	}
	return n
}

func (m *PlayableInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	l = len(m.Subtitle)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	l = len(m.Artist)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	l = len(m.Album)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	if m.ReleaseDate != 0 {
		n += 1 + sovAmp(uint64(m.ReleaseDate))
	}
	if m.Duration != 0 {
		n += 9
	}
	if m.Flags != 0 {
		n += 1 + sovAmp(uint64(m.Flags))
	}
	return n
}

func (m *MediaProviderInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CommonName)
	if l > 0 {
		n += 1 + l + sovAmp(uint64(l))
	}
	if m.RequiresSubscription {
		n += 2
	}
	if m.RequiresInternet {
		n += 2
	}
	return n
}

func sovAmp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAmp(x uint64) (n int) {
	return sovAmp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *LoginInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LoginInfo{`,
		`UserID:` + fmt.Sprintf("%v", this.UserID) + `,`,
		`Pass:` + fmt.Sprintf("%v", this.Pass) + `,`,
		`TokenValue:` + fmt.Sprintf("%v", this.TokenValue) + `,`,
		`TokenExpires:` + fmt.Sprintf("%v", this.TokenExpires) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PlayableInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PlayableInfo{`,
		`Title:` + fmt.Sprintf("%v", this.Title) + `,`,
		`Subtitle:` + fmt.Sprintf("%v", this.Subtitle) + `,`,
		`Artist:` + fmt.Sprintf("%v", this.Artist) + `,`,
		`Album:` + fmt.Sprintf("%v", this.Album) + `,`,
		`ReleaseDate:` + fmt.Sprintf("%v", this.ReleaseDate) + `,`,
		`Duration:` + fmt.Sprintf("%v", this.Duration) + `,`,
		`Flags:` + fmt.Sprintf("%v", this.Flags) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MediaProviderInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MediaProviderInfo{`,
		`CommonName:` + fmt.Sprintf("%v", this.CommonName) + `,`,
		`RequiresSubscription:` + fmt.Sprintf("%v", this.RequiresSubscription) + `,`,
		`RequiresInternet:` + fmt.Sprintf("%v", this.RequiresInternet) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAmp(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *LoginInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pass", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pass = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenExpires", wireType)
			}
			m.TokenExpires = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenExpires |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAmp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayableInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayableInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayableInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subtitle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subtitle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Artist", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Artist = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Album", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Album = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseDate", wireType)
			}
			m.ReleaseDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReleaseDate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Duration = float64(math.Float64frombits(v))
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= PlayableFlags(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAmp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MediaProviderInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MediaProviderInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MediaProviderInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommonName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiresSubscription", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequiresSubscription = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiresInternet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequiresInternet = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAmp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAmp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAmp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAmp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAmp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAmp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAmp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAmp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAmp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAmp = fmt.Errorf("proto: unexpected end of group")
)
