// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: amp/apps/amp-app-av/av/api.av.proto

package av

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	amp "github.com/amp-3d/amp-sdk-go/amp"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MediaFlags int32

const (
	MediaFlags_Unknown      MediaFlags = 0
	MediaFlags_HasAudio     MediaFlags = 256
	MediaFlags_HasVideo     MediaFlags = 512
	MediaFlags_HasSpeech    MediaFlags = 1024
	MediaFlags_NeedsNetwork MediaFlags = 2048
	MediaFlags_IsLive       MediaFlags = 1
	MediaFlags_IsSeekable   MediaFlags = 2
	MediaFlags_IsUnending   MediaFlags = 4
	// When set, the user is more likely to skipping short intervals than switch media items.
	MediaFlags_SkipIsLikely MediaFlags = 16
)

var MediaFlags_name = map[int32]string{
	0:    "MediaFlags_Unknown",
	256:  "MediaFlags_HasAudio",
	512:  "MediaFlags_HasVideo",
	1024: "MediaFlags_HasSpeech",
	2048: "MediaFlags_NeedsNetwork",
	1:    "MediaFlags_IsLive",
	2:    "MediaFlags_IsSeekable",
	4:    "MediaFlags_IsUnending",
	16:   "MediaFlags_SkipIsLikely",
}

var MediaFlags_value = map[string]int32{
	"MediaFlags_Unknown":      0,
	"MediaFlags_HasAudio":     256,
	"MediaFlags_HasVideo":     512,
	"MediaFlags_HasSpeech":    1024,
	"MediaFlags_NeedsNetwork": 2048,
	"MediaFlags_IsLive":       1,
	"MediaFlags_IsSeekable":   2,
	"MediaFlags_IsUnending":   4,
	"MediaFlags_SkipIsLikely": 16,
}

func (MediaFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{0}
}

type LoginInfo struct {
	UserID       string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Pass         string `protobuf:"bytes,2,opt,name=Pass,proto3" json:"Pass,omitempty"`
	TokenValue   string `protobuf:"bytes,3,opt,name=TokenValue,proto3" json:"TokenValue,omitempty"`
	TokenExpires int64  `protobuf:"varint,4,opt,name=TokenExpires,proto3" json:"TokenExpires,omitempty"`
}

func (m *LoginInfo) Reset()      { *m = LoginInfo{} }
func (*LoginInfo) ProtoMessage() {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{0}
}
func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return m.Size()
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginInfo) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *LoginInfo) GetTokenValue() string {
	if m != nil {
		return m.TokenValue
	}
	return ""
}

func (m *LoginInfo) GetTokenExpires() int64 {
	if m != nil {
		return m.TokenExpires
	}
	return 0
}

type LoginCreateResponse struct {
	TimestampExpires string `protobuf:"bytes,1,opt,name=timestamp_expires,json=timestampExpires,proto3" json:"timestamp_expires,omitempty"`
	Token            string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ChatStatus       string `protobuf:"bytes,3,opt,name=chat_status,json=chatStatus,proto3" json:"chat_status,omitempty"`
	ChatVersion      int64  `protobuf:"varint,4,opt,name=chat_version,json=chatVersion,proto3" json:"chat_version,omitempty"`
}

func (m *LoginCreateResponse) Reset()      { *m = LoginCreateResponse{} }
func (*LoginCreateResponse) ProtoMessage() {}
func (*LoginCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{1}
}
func (m *LoginCreateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginCreateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCreateResponse.Merge(m, src)
}
func (m *LoginCreateResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoginCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCreateResponse proto.InternalMessageInfo

func (m *LoginCreateResponse) GetTimestampExpires() string {
	if m != nil {
		return m.TimestampExpires
	}
	return ""
}

func (m *LoginCreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginCreateResponse) GetChatStatus() string {
	if m != nil {
		return m.ChatStatus
	}
	return ""
}

func (m *LoginCreateResponse) GetChatVersion() int64 {
	if m != nil {
		return m.ChatVersion
	}
	return 0
}

type CategoryInfo struct {
	Id                uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category          string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title             string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description       string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type              string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Subtype           string `protobuf:"bytes,6,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Image             string `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	TimestampCreated  string `protobuf:"bytes,8,opt,name=timestamp_created,json=timestampCreated,proto3" json:"timestamp_created,omitempty"`
	TimestampModified string `protobuf:"bytes,9,opt,name=timestamp_modified,json=timestampModified,proto3" json:"timestamp_modified,omitempty"`
}

func (m *CategoryInfo) Reset()      { *m = CategoryInfo{} }
func (*CategoryInfo) ProtoMessage() {}
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{2}
}
func (m *CategoryInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CategoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CategoryInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CategoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryInfo.Merge(m, src)
}
func (m *CategoryInfo) XXX_Size() int {
	return m.Size()
}
func (m *CategoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryInfo proto.InternalMessageInfo

func (m *CategoryInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CategoryInfo) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *CategoryInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CategoryInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CategoryInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CategoryInfo) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *CategoryInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CategoryInfo) GetTimestampCreated() string {
	if m != nil {
		return m.TimestampCreated
	}
	return ""
}

func (m *CategoryInfo) GetTimestampModified() string {
	if m != nil {
		return m.TimestampModified
	}
	return ""
}

type StationInfo struct {
	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type        string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Subtype     string `protobuf:"bytes,6,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Image       string `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Author      string `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	Url         string `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Summary     string `protobuf:"bytes,10,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (m *StationInfo) Reset()      { *m = StationInfo{} }
func (*StationInfo) ProtoMessage() {}
func (*StationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{3}
}
func (m *StationInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StationInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationInfo.Merge(m, src)
}
func (m *StationInfo) XXX_Size() int {
	return m.Size()
}
func (m *StationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StationInfo proto.InternalMessageInfo

func (m *StationInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StationInfo) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *StationInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StationInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StationInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StationInfo) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *StationInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *StationInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *StationInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StationInfo) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

// Invokes an fully featured media player over a panel.
type PlayableMedia struct {
	Flags       MediaFlags  `protobuf:"varint,1,opt,name=Flags,proto3,enum=av.MediaFlags" json:"Flags,omitempty"`
	Media       *amp.TagTab `protobuf:"bytes,3,opt,name=Media,proto3" json:"Media,omitempty"`
	Author      *amp.TagTab `protobuf:"bytes,5,opt,name=Author,proto3" json:"Author,omitempty"`
	Collection  *amp.TagTab `protobuf:"bytes,7,opt,name=Collection,proto3" json:"Collection,omitempty"`
	ItemNumber  int32       `protobuf:"varint,10,opt,name=ItemNumber,proto3" json:"ItemNumber,omitempty"`
	Seconds     float64     `protobuf:"fixed64,11,opt,name=Seconds,proto3" json:"Seconds,omitempty"`
	Popularity  float32     `protobuf:"fixed32,12,opt,name=Popularity,proto3" json:"Popularity,omitempty"`
	ReleaseDate int64       `protobuf:"varint,14,opt,name=ReleaseDate,proto3" json:"ReleaseDate,omitempty"`
}

func (m *PlayableMedia) Reset()      { *m = PlayableMedia{} }
func (*PlayableMedia) ProtoMessage() {}
func (*PlayableMedia) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{4}
}
func (m *PlayableMedia) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlayableMedia) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlayableMedia.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlayableMedia) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayableMedia.Merge(m, src)
}
func (m *PlayableMedia) XXX_Size() int {
	return m.Size()
}
func (m *PlayableMedia) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayableMedia.DiscardUnknown(m)
}

var xxx_messageInfo_PlayableMedia proto.InternalMessageInfo

func (m *PlayableMedia) GetFlags() MediaFlags {
	if m != nil {
		return m.Flags
	}
	return MediaFlags_Unknown
}

func (m *PlayableMedia) GetMedia() *amp.TagTab {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *PlayableMedia) GetAuthor() *amp.TagTab {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PlayableMedia) GetCollection() *amp.TagTab {
	if m != nil {
		return m.Collection
	}
	return nil
}

func (m *PlayableMedia) GetItemNumber() int32 {
	if m != nil {
		return m.ItemNumber
	}
	return 0
}

func (m *PlayableMedia) GetSeconds() float64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *PlayableMedia) GetPopularity() float32 {
	if m != nil {
		return m.Popularity
	}
	return 0
}

func (m *PlayableMedia) GetReleaseDate() int64 {
	if m != nil {
		return m.ReleaseDate
	}
	return 0
}

type MediaPlaylist struct {
	TotalItems    int32   `protobuf:"varint,5,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	TotalDuration float64 `protobuf:"fixed64,6,opt,name=TotalDuration,proto3" json:"TotalDuration,omitempty"`
}

func (m *MediaPlaylist) Reset()      { *m = MediaPlaylist{} }
func (*MediaPlaylist) ProtoMessage() {}
func (*MediaPlaylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{5}
}
func (m *MediaPlaylist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MediaPlaylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MediaPlaylist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MediaPlaylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaPlaylist.Merge(m, src)
}
func (m *MediaPlaylist) XXX_Size() int {
	return m.Size()
}
func (m *MediaPlaylist) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaPlaylist.DiscardUnknown(m)
}

var xxx_messageInfo_MediaPlaylist proto.InternalMessageInfo

func (m *MediaPlaylist) GetTotalItems() int32 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *MediaPlaylist) GetTotalDuration() float64 {
	if m != nil {
		return m.TotalDuration
	}
	return 0
}

type MediaProviderInfo struct {
	CommonName           string `protobuf:"bytes,1,opt,name=CommonName,proto3" json:"CommonName,omitempty"`
	RequiresSubscription bool   `protobuf:"varint,2,opt,name=RequiresSubscription,proto3" json:"RequiresSubscription,omitempty"`
	RequiresInternet     bool   `protobuf:"varint,3,opt,name=RequiresInternet,proto3" json:"RequiresInternet,omitempty"`
}

func (m *MediaProviderInfo) Reset()      { *m = MediaProviderInfo{} }
func (*MediaProviderInfo) ProtoMessage() {}
func (*MediaProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0c9b22ad631331, []int{6}
}
func (m *MediaProviderInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MediaProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MediaProviderInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MediaProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaProviderInfo.Merge(m, src)
}
func (m *MediaProviderInfo) XXX_Size() int {
	return m.Size()
}
func (m *MediaProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MediaProviderInfo proto.InternalMessageInfo

func (m *MediaProviderInfo) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *MediaProviderInfo) GetRequiresSubscription() bool {
	if m != nil {
		return m.RequiresSubscription
	}
	return false
}

func (m *MediaProviderInfo) GetRequiresInternet() bool {
	if m != nil {
		return m.RequiresInternet
	}
	return false
}

func init() {
	proto.RegisterEnum("av.MediaFlags", MediaFlags_name, MediaFlags_value)
	proto.RegisterType((*LoginInfo)(nil), "av.LoginInfo")
	proto.RegisterType((*LoginCreateResponse)(nil), "av.LoginCreateResponse")
	proto.RegisterType((*CategoryInfo)(nil), "av.CategoryInfo")
	proto.RegisterType((*StationInfo)(nil), "av.StationInfo")
	proto.RegisterType((*PlayableMedia)(nil), "av.PlayableMedia")
	proto.RegisterType((*MediaPlaylist)(nil), "av.MediaPlaylist")
	proto.RegisterType((*MediaProviderInfo)(nil), "av.MediaProviderInfo")
}

func init() {
	proto.RegisterFile("amp/apps/amp-app-av/av/api.av.proto", fileDescriptor_de0c9b22ad631331)
}

var fileDescriptor_de0c9b22ad631331 = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xbf, 0x6f, 0xdb, 0x46,
	0x14, 0xd6, 0xd1, 0x96, 0x2c, 0x3f, 0xd9, 0x06, 0x7d, 0x71, 0x5c, 0x26, 0x2d, 0x58, 0x85, 0xc9,
	0x60, 0x24, 0xb0, 0x0d, 0xb8, 0x5b, 0x37, 0xd7, 0x6e, 0x51, 0x01, 0xb1, 0x61, 0x50, 0xb6, 0x57,
	0xe3, 0x24, 0xbe, 0xc8, 0x07, 0x91, 0x3c, 0x96, 0x77, 0x54, 0x2a, 0x74, 0xd1, 0x9f, 0x50, 0xb4,
	0x6b, 0xe7, 0xa2, 0xe8, 0x5f, 0xd2, 0xd1, 0x63, 0xc6, 0x5a, 0x5e, 0x3a, 0x66, 0x2d, 0xba, 0x14,
	0x77, 0x47, 0x45, 0x54, 0xd5, 0x7f, 0x20, 0x80, 0x06, 0x7e, 0xdf, 0xf7, 0xf8, 0x7e, 0x7c, 0xf7,
	0x8e, 0x82, 0xe7, 0x2c, 0xc9, 0x0e, 0x59, 0x96, 0xc9, 0x43, 0x96, 0x64, 0xfb, 0x2c, 0xcb, 0xf6,
	0xd9, 0xe8, 0x50, 0xff, 0x32, 0x7e, 0xc0, 0x46, 0x07, 0x59, 0x2e, 0x94, 0xa0, 0x0e, 0x1b, 0x3d,
	0xdd, 0xb6, 0x81, 0xfc, 0x80, 0x25, 0x99, 0xa5, 0x83, 0x1f, 0x60, 0xfd, 0xb5, 0x18, 0xf0, 0xb4,
	0x93, 0xbe, 0x11, 0x74, 0x17, 0x1a, 0x57, 0x12, 0xf3, 0xce, 0xa9, 0x47, 0xda, 0x64, 0x6f, 0x3d,
	0x2c, 0x11, 0xa5, 0xb0, 0x7a, 0xc1, 0xa4, 0xf4, 0x1c, 0xc3, 0x9a, 0x67, 0xea, 0x03, 0x5c, 0x8a,
	0x21, 0xa6, 0xd7, 0x2c, 0x2e, 0xd0, 0x5b, 0x31, 0x4a, 0x85, 0xa1, 0x01, 0x6c, 0x18, 0xf4, 0xf5,
	0xf7, 0x19, 0xcf, 0x51, 0x7a, 0xab, 0x6d, 0xb2, 0xb7, 0x12, 0x2e, 0x70, 0xc1, 0x2f, 0x04, 0x1e,
	0x99, 0xea, 0x27, 0x39, 0x32, 0x85, 0x21, 0xca, 0x4c, 0xa4, 0x12, 0xe9, 0x2b, 0xd8, 0x56, 0x3c,
	0x41, 0xa9, 0x58, 0x92, 0xdd, 0x60, 0x99, 0xc0, 0xb6, 0xe4, 0x7e, 0x10, 0xca, 0x24, 0x74, 0x07,
	0xea, 0x4a, 0x27, 0x2d, 0xbb, 0xb3, 0x80, 0x7e, 0x0e, 0xad, 0xfe, 0x2d, 0x53, 0x37, 0x52, 0x31,
	0x55, 0xc8, 0x59, 0x7f, 0x9a, 0xea, 0x1a, 0x86, 0x3e, 0x83, 0x0d, 0x13, 0x30, 0xc2, 0x5c, 0x72,
	0x91, 0x96, 0xfd, 0x99, 0x97, 0xae, 0x2d, 0x15, 0xfc, 0xe4, 0xc0, 0xc6, 0x09, 0x53, 0x38, 0x10,
	0xf9, 0xd8, 0xf8, 0xb3, 0x05, 0x0e, 0x8f, 0x4c, 0x23, 0x9b, 0xa1, 0xc3, 0x23, 0xfa, 0x14, 0x9a,
	0xfd, 0x52, 0x2f, 0xab, 0x7f, 0xc0, 0xa6, 0x2d, 0xae, 0xe2, 0x99, 0x35, 0x16, 0xd0, 0x36, 0xb4,
	0x22, 0x94, 0xfd, 0x9c, 0x67, 0x6a, 0x56, 0x74, 0x3d, 0xac, 0x52, 0xda, 0x6b, 0x35, 0xce, 0xd0,
	0xab, 0x5b, 0xaf, 0xf5, 0x33, 0xf5, 0x60, 0x4d, 0x16, 0x3d, 0x43, 0x37, 0x0c, 0x3d, 0x83, 0xba,
	0x0a, 0x4f, 0xd8, 0x00, 0xbd, 0x35, 0x5b, 0xc5, 0x80, 0x45, 0xff, 0xfa, 0xc6, 0xdb, 0xc8, 0x6b,
	0xfe, 0xc7, 0x3f, 0xeb, 0x79, 0x44, 0xf7, 0x81, 0xce, 0x83, 0x13, 0x11, 0xf1, 0x37, 0x1c, 0x23,
	0x6f, 0xdd, 0x44, 0xcf, 0xd3, 0x9c, 0x95, 0x42, 0xf0, 0x37, 0x81, 0x96, 0xb6, 0x90, 0x8b, 0xf4,
	0xa3, 0xf2, 0x64, 0x17, 0x1a, 0xac, 0x50, 0xb7, 0x22, 0x2f, 0x8d, 0x28, 0x11, 0x75, 0x61, 0xa5,
	0xc8, 0xe3, 0x72, 0x5e, 0xfd, 0x68, 0x33, 0x27, 0x09, 0xcb, 0xc7, 0x1e, 0xcc, 0x32, 0x1b, 0x18,
	0xfc, 0xea, 0xc0, 0xe6, 0x45, 0xcc, 0xc6, 0xac, 0x17, 0xe3, 0x19, 0x46, 0x9c, 0xd1, 0x17, 0x50,
	0xff, 0x26, 0x66, 0x03, 0xbb, 0x9d, 0x5b, 0x47, 0x5b, 0xfa, 0xbe, 0x19, 0xc5, 0xb0, 0xa1, 0x15,
	0xe9, 0x33, 0xa8, 0x1b, 0xd2, 0xcc, 0xdd, 0x3a, 0x6a, 0x99, 0xfb, 0x77, 0xc9, 0x06, 0x97, 0xac,
	0x17, 0x5a, 0x85, 0x3e, 0x87, 0xc6, 0xb1, 0x6d, 0xaf, 0xbe, 0x1c, 0x53, 0x4a, 0xf4, 0x15, 0xc0,
	0x89, 0x88, 0x63, 0xec, 0x1b, 0xa3, 0xd6, 0x96, 0x03, 0x2b, 0xb2, 0xbe, 0xa0, 0x1d, 0x85, 0xc9,
	0x79, 0x91, 0xf4, 0x30, 0x37, 0x93, 0xd4, 0xc3, 0x0a, 0xa3, 0xc7, 0xec, 0x62, 0x5f, 0xa4, 0x91,
	0xf4, 0x5a, 0x6d, 0xb2, 0x47, 0xc2, 0x19, 0xd4, 0x6f, 0x5e, 0x88, 0xac, 0x88, 0x59, 0xce, 0xd5,
	0xd8, 0xdb, 0x68, 0x93, 0x3d, 0x27, 0xac, 0x30, 0xfa, 0xc0, 0x42, 0x8c, 0x91, 0x49, 0x3c, 0x65,
	0x0a, 0xbd, 0x2d, 0x7b, 0x73, 0x2a, 0x54, 0x70, 0x05, 0x9b, 0x66, 0x2c, 0x6d, 0x56, 0xcc, 0xa5,
	0xb2, 0x5f, 0x0b, 0xc5, 0x62, 0x5d, 0x5f, 0x9a, 0x11, 0xeb, 0x61, 0x85, 0xa1, 0x2f, 0x60, 0xd3,
	0xa0, 0xd3, 0x22, 0x37, 0xab, 0x65, 0xce, 0x94, 0x84, 0x8b, 0x64, 0xf0, 0x33, 0x81, 0x6d, 0x9b,
	0x37, 0x17, 0x23, 0x1e, 0x61, 0x6e, 0x36, 0xd0, 0xd7, 0xae, 0x24, 0x89, 0x48, 0xcf, 0x59, 0x82,
	0xe5, 0x67, 0xa2, 0xc2, 0xd0, 0x23, 0xd8, 0x09, 0xf1, 0xbb, 0x42, 0x7f, 0x2c, 0xba, 0x45, 0x6f,
	0xbe, 0x68, 0x7a, 0x3b, 0x9b, 0xe1, 0xff, 0x6a, 0xf4, 0x25, 0xb8, 0x33, 0xbe, 0x93, 0x2a, 0xcc,
	0x53, 0x54, 0xe6, 0xf0, 0x9a, 0xe1, 0x12, 0xff, 0xf2, 0x1f, 0x02, 0x30, 0x3f, 0x73, 0xba, 0x0b,
	0x74, 0x8e, 0x6e, 0xae, 0xd2, 0x61, 0x2a, 0xde, 0xa6, 0x6e, 0x8d, 0x7a, 0xf0, 0xa8, 0xc2, 0x7f,
	0xcb, 0xe4, 0x71, 0x11, 0x71, 0xe1, 0x4e, 0x9c, 0x65, 0xe5, 0x9a, 0x47, 0x28, 0xdc, 0xc9, 0x2a,
	0x7d, 0x02, 0x3b, 0x8b, 0x4a, 0x37, 0x43, 0xec, 0xdf, 0xba, 0x93, 0x26, 0xfd, 0x0c, 0x3e, 0xa9,
	0x48, 0xe7, 0x88, 0x91, 0x3c, 0x47, 0xf5, 0x56, 0xe4, 0x43, 0x77, 0xe2, 0xd2, 0xc7, 0xa5, 0x51,
	0x56, 0xed, 0xc8, 0xd7, 0x7c, 0x84, 0x2e, 0xa1, 0x4f, 0xe0, 0xf1, 0x02, 0xdd, 0x45, 0x1c, 0xea,
	0x65, 0x76, 0x9d, 0x25, 0xe9, 0x2a, 0xc5, 0x34, 0xe2, 0xe9, 0xc0, 0x5d, 0xa5, 0x9f, 0x2e, 0x94,
	0xea, 0x0e, 0x79, 0xa6, 0x13, 0x0e, 0x31, 0x1e, 0xbb, 0xee, 0x57, 0x5f, 0xde, 0xdd, 0xfb, 0xb5,
	0x77, 0xf7, 0x7e, 0xed, 0xfd, 0xbd, 0x4f, 0x26, 0x53, 0x9f, 0xfc, 0x36, 0xf5, 0xc9, 0x1f, 0x53,
	0x9f, 0xdc, 0x4d, 0x7d, 0xf2, 0xe7, 0xd4, 0x27, 0x7f, 0x4d, 0xfd, 0xda, 0xfb, 0xa9, 0x4f, 0x7e,
	0x7c, 0xf0, 0x6b, 0x77, 0x0f, 0x7e, 0xed, 0xdd, 0x83, 0x5f, 0xfb, 0xdd, 0x59, 0x39, 0x3e, 0xbb,
	0xe8, 0x35, 0xcc, 0x7f, 0xd0, 0x17, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xc5, 0x09, 0xb5,
	0xc1, 0x06, 0x00, 0x00,
}

func (x MediaFlags) String() string {
	s, ok := MediaFlags_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *LoginInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginInfo)
	if !ok {
		that2, ok := that.(LoginInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if this.Pass != that1.Pass {
		return false
	}
	if this.TokenValue != that1.TokenValue {
		return false
	}
	if this.TokenExpires != that1.TokenExpires {
		return false
	}
	return true
}
func (this *LoginCreateResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginCreateResponse)
	if !ok {
		that2, ok := that.(LoginCreateResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TimestampExpires != that1.TimestampExpires {
		return false
	}
	if this.Token != that1.Token {
		return false
	}
	if this.ChatStatus != that1.ChatStatus {
		return false
	}
	if this.ChatVersion != that1.ChatVersion {
		return false
	}
	return true
}
func (this *CategoryInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CategoryInfo)
	if !ok {
		that2, ok := that.(CategoryInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Category != that1.Category {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Subtype != that1.Subtype {
		return false
	}
	if this.Image != that1.Image {
		return false
	}
	if this.TimestampCreated != that1.TimestampCreated {
		return false
	}
	if this.TimestampModified != that1.TimestampModified {
		return false
	}
	return true
}
func (this *StationInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StationInfo)
	if !ok {
		that2, ok := that.(StationInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Category != that1.Category {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Subtype != that1.Subtype {
		return false
	}
	if this.Image != that1.Image {
		return false
	}
	if this.Author != that1.Author {
		return false
	}
	if this.Url != that1.Url {
		return false
	}
	if this.Summary != that1.Summary {
		return false
	}
	return true
}
func (this *PlayableMedia) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PlayableMedia)
	if !ok {
		that2, ok := that.(PlayableMedia)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Flags != that1.Flags {
		return false
	}
	if !this.Media.Equal(that1.Media) {
		return false
	}
	if !this.Author.Equal(that1.Author) {
		return false
	}
	if !this.Collection.Equal(that1.Collection) {
		return false
	}
	if this.ItemNumber != that1.ItemNumber {
		return false
	}
	if this.Seconds != that1.Seconds {
		return false
	}
	if this.Popularity != that1.Popularity {
		return false
	}
	if this.ReleaseDate != that1.ReleaseDate {
		return false
	}
	return true
}
func (this *MediaPlaylist) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MediaPlaylist)
	if !ok {
		that2, ok := that.(MediaPlaylist)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TotalItems != that1.TotalItems {
		return false
	}
	if this.TotalDuration != that1.TotalDuration {
		return false
	}
	return true
}
func (this *MediaProviderInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MediaProviderInfo)
	if !ok {
		that2, ok := that.(MediaProviderInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CommonName != that1.CommonName {
		return false
	}
	if this.RequiresSubscription != that1.RequiresSubscription {
		return false
	}
	if this.RequiresInternet != that1.RequiresInternet {
		return false
	}
	return true
}
func (this *LoginInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&av.LoginInfo{")
	s = append(s, "UserID: "+fmt.Sprintf("%#v", this.UserID)+",\n")
	s = append(s, "Pass: "+fmt.Sprintf("%#v", this.Pass)+",\n")
	s = append(s, "TokenValue: "+fmt.Sprintf("%#v", this.TokenValue)+",\n")
	s = append(s, "TokenExpires: "+fmt.Sprintf("%#v", this.TokenExpires)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *LoginCreateResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&av.LoginCreateResponse{")
	s = append(s, "TimestampExpires: "+fmt.Sprintf("%#v", this.TimestampExpires)+",\n")
	s = append(s, "Token: "+fmt.Sprintf("%#v", this.Token)+",\n")
	s = append(s, "ChatStatus: "+fmt.Sprintf("%#v", this.ChatStatus)+",\n")
	s = append(s, "ChatVersion: "+fmt.Sprintf("%#v", this.ChatVersion)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CategoryInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 13)
	s = append(s, "&av.CategoryInfo{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Category: "+fmt.Sprintf("%#v", this.Category)+",\n")
	s = append(s, "Title: "+fmt.Sprintf("%#v", this.Title)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Subtype: "+fmt.Sprintf("%#v", this.Subtype)+",\n")
	s = append(s, "Image: "+fmt.Sprintf("%#v", this.Image)+",\n")
	s = append(s, "TimestampCreated: "+fmt.Sprintf("%#v", this.TimestampCreated)+",\n")
	s = append(s, "TimestampModified: "+fmt.Sprintf("%#v", this.TimestampModified)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StationInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&av.StationInfo{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Category: "+fmt.Sprintf("%#v", this.Category)+",\n")
	s = append(s, "Title: "+fmt.Sprintf("%#v", this.Title)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Subtype: "+fmt.Sprintf("%#v", this.Subtype)+",\n")
	s = append(s, "Image: "+fmt.Sprintf("%#v", this.Image)+",\n")
	s = append(s, "Author: "+fmt.Sprintf("%#v", this.Author)+",\n")
	s = append(s, "Url: "+fmt.Sprintf("%#v", this.Url)+",\n")
	s = append(s, "Summary: "+fmt.Sprintf("%#v", this.Summary)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PlayableMedia) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&av.PlayableMedia{")
	s = append(s, "Flags: "+fmt.Sprintf("%#v", this.Flags)+",\n")
	if this.Media != nil {
		s = append(s, "Media: "+fmt.Sprintf("%#v", this.Media)+",\n")
	}
	if this.Author != nil {
		s = append(s, "Author: "+fmt.Sprintf("%#v", this.Author)+",\n")
	}
	if this.Collection != nil {
		s = append(s, "Collection: "+fmt.Sprintf("%#v", this.Collection)+",\n")
	}
	s = append(s, "ItemNumber: "+fmt.Sprintf("%#v", this.ItemNumber)+",\n")
	s = append(s, "Seconds: "+fmt.Sprintf("%#v", this.Seconds)+",\n")
	s = append(s, "Popularity: "+fmt.Sprintf("%#v", this.Popularity)+",\n")
	s = append(s, "ReleaseDate: "+fmt.Sprintf("%#v", this.ReleaseDate)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MediaPlaylist) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&av.MediaPlaylist{")
	s = append(s, "TotalItems: "+fmt.Sprintf("%#v", this.TotalItems)+",\n")
	s = append(s, "TotalDuration: "+fmt.Sprintf("%#v", this.TotalDuration)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MediaProviderInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&av.MediaProviderInfo{")
	s = append(s, "CommonName: "+fmt.Sprintf("%#v", this.CommonName)+",\n")
	s = append(s, "RequiresSubscription: "+fmt.Sprintf("%#v", this.RequiresSubscription)+",\n")
	s = append(s, "RequiresInternet: "+fmt.Sprintf("%#v", this.RequiresInternet)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringApiAv(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *LoginInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenExpires != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.TokenExpires))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TokenValue) > 0 {
		i -= len(m.TokenValue)
		copy(dAtA[i:], m.TokenValue)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.TokenValue)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Pass) > 0 {
		i -= len(m.Pass)
		copy(dAtA[i:], m.Pass)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Pass)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserID) > 0 {
		i -= len(m.UserID)
		copy(dAtA[i:], m.UserID)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.UserID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoginCreateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginCreateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginCreateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChatVersion != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.ChatVersion))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChatStatus) > 0 {
		i -= len(m.ChatStatus)
		copy(dAtA[i:], m.ChatStatus)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.ChatStatus)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TimestampExpires) > 0 {
		i -= len(m.TimestampExpires)
		copy(dAtA[i:], m.TimestampExpires)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.TimestampExpires)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CategoryInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CategoryInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CategoryInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TimestampModified) > 0 {
		i -= len(m.TimestampModified)
		copy(dAtA[i:], m.TimestampModified)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.TimestampModified)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.TimestampCreated) > 0 {
		i -= len(m.TimestampCreated)
		copy(dAtA[i:], m.TimestampCreated)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.TimestampCreated)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Subtype) > 0 {
		i -= len(m.Subtype)
		copy(dAtA[i:], m.Subtype)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Subtype)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StationInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StationInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StationInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Summary) > 0 {
		i -= len(m.Summary)
		copy(dAtA[i:], m.Summary)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Summary)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Subtype) > 0 {
		i -= len(m.Subtype)
		copy(dAtA[i:], m.Subtype)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Subtype)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PlayableMedia) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayableMedia) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlayableMedia) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReleaseDate != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.ReleaseDate))
		i--
		dAtA[i] = 0x70
	}
	if m.Popularity != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Popularity))))
		i--
		dAtA[i] = 0x65
	}
	if m.Seconds != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Seconds))))
		i--
		dAtA[i] = 0x59
	}
	if m.ItemNumber != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.ItemNumber))
		i--
		dAtA[i] = 0x50
	}
	if m.Collection != nil {
		{
			size, err := m.Collection.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApiAv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Author != nil {
		{
			size, err := m.Author.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApiAv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Media != nil {
		{
			size, err := m.Media.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApiAv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Flags != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.Flags))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MediaPlaylist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MediaPlaylist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MediaPlaylist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalDuration != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.TotalDuration))))
		i--
		dAtA[i] = 0x31
	}
	if m.TotalItems != 0 {
		i = encodeVarintApiAv(dAtA, i, uint64(m.TotalItems))
		i--
		dAtA[i] = 0x28
	}
	return len(dAtA) - i, nil
}

func (m *MediaProviderInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MediaProviderInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MediaProviderInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequiresInternet {
		i--
		if m.RequiresInternet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.RequiresSubscription {
		i--
		if m.RequiresSubscription {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.CommonName) > 0 {
		i -= len(m.CommonName)
		copy(dAtA[i:], m.CommonName)
		i = encodeVarintApiAv(dAtA, i, uint64(len(m.CommonName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApiAv(dAtA []byte, offset int, v uint64) int {
	offset -= sovApiAv(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LoginInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserID)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Pass)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.TokenValue)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	if m.TokenExpires != 0 {
		n += 1 + sovApiAv(uint64(m.TokenExpires))
	}
	return n
}

func (m *LoginCreateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TimestampExpires)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.ChatStatus)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	if m.ChatVersion != 0 {
		n += 1 + sovApiAv(uint64(m.ChatVersion))
	}
	return n
}

func (m *CategoryInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovApiAv(uint64(m.Id))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Subtype)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.TimestampCreated)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.TimestampModified)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	return n
}

func (m *StationInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovApiAv(uint64(m.Id))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Subtype)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	l = len(m.Summary)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	return n
}

func (m *PlayableMedia) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Flags != 0 {
		n += 1 + sovApiAv(uint64(m.Flags))
	}
	if m.Media != nil {
		l = m.Media.Size()
		n += 1 + l + sovApiAv(uint64(l))
	}
	if m.Author != nil {
		l = m.Author.Size()
		n += 1 + l + sovApiAv(uint64(l))
	}
	if m.Collection != nil {
		l = m.Collection.Size()
		n += 1 + l + sovApiAv(uint64(l))
	}
	if m.ItemNumber != 0 {
		n += 1 + sovApiAv(uint64(m.ItemNumber))
	}
	if m.Seconds != 0 {
		n += 9
	}
	if m.Popularity != 0 {
		n += 5
	}
	if m.ReleaseDate != 0 {
		n += 1 + sovApiAv(uint64(m.ReleaseDate))
	}
	return n
}

func (m *MediaPlaylist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalItems != 0 {
		n += 1 + sovApiAv(uint64(m.TotalItems))
	}
	if m.TotalDuration != 0 {
		n += 9
	}
	return n
}

func (m *MediaProviderInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CommonName)
	if l > 0 {
		n += 1 + l + sovApiAv(uint64(l))
	}
	if m.RequiresSubscription {
		n += 2
	}
	if m.RequiresInternet {
		n += 2
	}
	return n
}

func sovApiAv(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApiAv(x uint64) (n int) {
	return sovApiAv(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *LoginInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LoginInfo{`,
		`UserID:` + fmt.Sprintf("%v", this.UserID) + `,`,
		`Pass:` + fmt.Sprintf("%v", this.Pass) + `,`,
		`TokenValue:` + fmt.Sprintf("%v", this.TokenValue) + `,`,
		`TokenExpires:` + fmt.Sprintf("%v", this.TokenExpires) + `,`,
		`}`,
	}, "")
	return s
}
func (this *LoginCreateResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LoginCreateResponse{`,
		`TimestampExpires:` + fmt.Sprintf("%v", this.TimestampExpires) + `,`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`ChatStatus:` + fmt.Sprintf("%v", this.ChatStatus) + `,`,
		`ChatVersion:` + fmt.Sprintf("%v", this.ChatVersion) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CategoryInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CategoryInfo{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Category:` + fmt.Sprintf("%v", this.Category) + `,`,
		`Title:` + fmt.Sprintf("%v", this.Title) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Subtype:` + fmt.Sprintf("%v", this.Subtype) + `,`,
		`Image:` + fmt.Sprintf("%v", this.Image) + `,`,
		`TimestampCreated:` + fmt.Sprintf("%v", this.TimestampCreated) + `,`,
		`TimestampModified:` + fmt.Sprintf("%v", this.TimestampModified) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StationInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StationInfo{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Category:` + fmt.Sprintf("%v", this.Category) + `,`,
		`Title:` + fmt.Sprintf("%v", this.Title) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Subtype:` + fmt.Sprintf("%v", this.Subtype) + `,`,
		`Image:` + fmt.Sprintf("%v", this.Image) + `,`,
		`Author:` + fmt.Sprintf("%v", this.Author) + `,`,
		`Url:` + fmt.Sprintf("%v", this.Url) + `,`,
		`Summary:` + fmt.Sprintf("%v", this.Summary) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PlayableMedia) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PlayableMedia{`,
		`Flags:` + fmt.Sprintf("%v", this.Flags) + `,`,
		`Media:` + strings.Replace(fmt.Sprintf("%v", this.Media), "TagTab", "amp.TagTab", 1) + `,`,
		`Author:` + strings.Replace(fmt.Sprintf("%v", this.Author), "TagTab", "amp.TagTab", 1) + `,`,
		`Collection:` + strings.Replace(fmt.Sprintf("%v", this.Collection), "TagTab", "amp.TagTab", 1) + `,`,
		`ItemNumber:` + fmt.Sprintf("%v", this.ItemNumber) + `,`,
		`Seconds:` + fmt.Sprintf("%v", this.Seconds) + `,`,
		`Popularity:` + fmt.Sprintf("%v", this.Popularity) + `,`,
		`ReleaseDate:` + fmt.Sprintf("%v", this.ReleaseDate) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MediaPlaylist) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MediaPlaylist{`,
		`TotalItems:` + fmt.Sprintf("%v", this.TotalItems) + `,`,
		`TotalDuration:` + fmt.Sprintf("%v", this.TotalDuration) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MediaProviderInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MediaProviderInfo{`,
		`CommonName:` + fmt.Sprintf("%v", this.CommonName) + `,`,
		`RequiresSubscription:` + fmt.Sprintf("%v", this.RequiresSubscription) + `,`,
		`RequiresInternet:` + fmt.Sprintf("%v", this.RequiresInternet) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringApiAv(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *LoginInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pass", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pass = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenExpires", wireType)
			}
			m.TokenExpires = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenExpires |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginCreateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginCreateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginCreateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampExpires", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampExpires = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChatStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChatStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChatVersion", wireType)
			}
			m.ChatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChatVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CategoryInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CategoryInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CategoryInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampCreated", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampCreated = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampModified", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampModified = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StationInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StationInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StationInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Summary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayableMedia) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayableMedia: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayableMedia: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= MediaFlags(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Media", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Media == nil {
				m.Media = &amp.TagTab{}
			}
			if err := m.Media.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Author == nil {
				m.Author = &amp.TagTab{}
			}
			if err := m.Author.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Collection == nil {
				m.Collection = &amp.TagTab{}
			}
			if err := m.Collection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemNumber", wireType)
			}
			m.ItemNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ItemNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seconds", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Seconds = float64(math.Float64frombits(v))
		case 12:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Popularity", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Popularity = float32(math.Float32frombits(v))
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseDate", wireType)
			}
			m.ReleaseDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReleaseDate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MediaPlaylist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MediaPlaylist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MediaPlaylist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalItems", wireType)
			}
			m.TotalItems = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalItems |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDuration", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.TotalDuration = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MediaProviderInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MediaProviderInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MediaProviderInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiAv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiAv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommonName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiresSubscription", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequiresSubscription = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiresInternet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequiresInternet = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApiAv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApiAv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApiAv(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApiAv
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApiAv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApiAv
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApiAv
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApiAv
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApiAv        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApiAv          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApiAv = fmt.Errorf("proto: unexpected end of group")
)
